# Set up models for edge or weight masking

## Workflow:
- Load model
- Use Task with clean and corrupt data, use ACDCPP and get the ACDCPP-style edges
- Convert ACDCPP-style edges to edge mask, get either edge superset of node superset
- Apply these masks to the mask training, either by limiting edge mask to only edge superset, node superset, or by limiting weight mask to node superset

- Also need to test other baselines, like regular finetuning

In [1]:
%load_ext autoreload
%autoreload 2
import os
import sys
sys.path.append('acdcpp/Automatic-Circuit-Discovery/')
sys.path.append('acdcpp/')
from acdc import TLACDCExperiment
from acdcpp.ACDCPPExperiment import ACDCPPExperiment

In [2]:
import os
import sys
import re

# import acdc
from acdc.TLACDCExperiment import TLACDCExperiment
from acdc.acdc_utils import TorchIndex, EdgeType
import numpy as np
import torch as t
from torch import Tensor
import einops
import itertools

from transformer_lens import HookedTransformer, ActivationCache

import tqdm.notebook as tqdm
import plotly
from rich import print as rprint
from rich.table import Table

from jaxtyping import Float, Bool
from typing import Callable, Tuple, Union, Dict, Optional

import torch

device = t.device('cuda') if t.cuda.is_available() else t.device('cpu')
print(f'Device: {device}')

Device: cuda


In [3]:
# set up pipeline from acdcpp to edge mask
model = HookedTransformer.from_pretrained(
    'gpt2-small',
    center_writing_weights=False,
    center_unembed=False,
    fold_ln=False,
    device=device,
)
model.set_use_hook_mlp_in(True)
model.set_use_split_qkv_input(True)
model.set_use_attn_result(True)



Loaded pretrained model gpt2-small into HookedTransformer


In [4]:
from tasks.ioi.IOITask import IOITask_old, IOITask
ioi_task = IOITask(batch_size=5, tokenizer=model.tokenizer, device=device, prep_acdcpp=True, acdcpp_N=25)
ioi_task.set_logit_diffs(model)

In [5]:
ioi_metric = ioi_task.get_acdcpp_metric()
def negative_abs_ioi_metric(logits: Float[Tensor, "batch seq_len d_vocab"]):
    return -abs(ioi_metric(logits))

with t.no_grad():
    clean_logits = model(ioi_task.clean_data.toks)
    corrupt_logits = model(ioi_task.corr_data.toks)
    clean_logit_diff = ioi_task.ave_logit_diff(clean_logits, ioi_task.clean_data).item()
    corrupt_logit_diff = ioi_task.ave_logit_diff(corrupt_logits, ioi_task.corr_data).item()

In [6]:
# Get clean and corrupt logit differences
with t.no_grad():
    clean_metric = ioi_metric(clean_logits, corrupt_logit_diff, clean_logit_diff, ioi_task.clean_data)
    corrupt_metric = ioi_metric(corrupt_logits, corrupt_logit_diff, clean_logit_diff, ioi_task.corr_data)

print(f'Clean direction: {clean_logit_diff}, Corrupt direction: {corrupt_logit_diff}')
print(f'Clean metric: {clean_metric}, Corrupt metric: {corrupt_metric}')

Clean direction: 3.040117025375366, Corrupt direction: 1.8117443323135376
Clean metric: 1.0, Corrupt metric: 0.0


In [7]:
from ACDCPPExperiment import ACDCPPExperiment
THRESHOLDS = [0.08, .15]#np.arange(0.005, 0.155, 0.005)
RUN_NAME = 'abs_edge'

acdcpp_exp = ACDCPPExperiment(
    model=model,
    clean_data=ioi_task.clean_data.toks,
    corr_data=ioi_task.corr_data.toks,
    acdc_metric=negative_abs_ioi_metric,
    acdcpp_metric=ioi_metric,
    thresholds=THRESHOLDS,
    run_name=RUN_NAME,
    verbose=False,
    attr_absolute_val=True,
    save_graphs_after=-100,
    pruning_mode='edge',
    no_pruned_nodes_attr=1,
    run_acdc=False,
    run_acdcpp=True,
)
# e=acdcpp_exp.setup_exp(0.0)

pruned_heads, num_passes, acdcpp_pruned_attrs, acdc_pruned_attrs, edges_after_acdcpp, edges_after_acdc = acdcpp_exp.run()

  0%|          | 0/2 [00:00<?, ?it/s]WARNING:root:cache_all is deprecated and will eventually be removed, use add_caching_hooks or run_with_cache


self.current_node=TLACDCInterpNode(blocks.11.hook_resid_post, [:])


Edge pruning: 100%|██████████| 1034/1034 [00:00<00:00, 282571.69it/s]


dict_keys([-1, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 12])


 50%|█████     | 1/2 [00:08<00:08,  9.00s/it]WARNING:root:cache_all is deprecated and will eventually be removed, use add_caching_hooks or run_with_cache


self.current_node=TLACDCInterpNode(blocks.11.hook_resid_post, [:])


100%|██████████| 2/2 [00:16<00:00,  8.23s/it]

dict_keys([-1, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 12])


In [8]:
import pickle
with open("masks/ioi_acdcpp_edges.pkl", "wb") as f:
    pickle.dump(edges_after_acdcpp, f)

In [9]:
from cb_utils.mask_utils import get_node_name

acdcpp_edges = set()
for edge in edges_after_acdcpp[0.08]:
    # split the edge into two nodes, e.g. blocks.1.attn.hook_result[:, :, 10]blocks.0.hook_mlp_in[:] into blocks.1.attn.hook_result[:, :, 10] and blocks.0.hook_mlp_in[:]
    node_1 = get_node_name(edge.split("]")[0]+"]", show_full_index=False)
    node_2 = get_node_name(edge.split("]")[1]+"]", show_full_index=False)
    if node_1 != node_2:
        acdcpp_edges.add((node_1, node_2))

Using device: cuda:0


In [10]:
from cb_utils.mask_utils import get_edge_mask_template, get_mask_from_edges, convert_mask_dict_to_params
edge_mask_template = get_edge_mask_template()
acdcpp_mask_dict = get_mask_from_edges(acdcpp_edges, edge_mask_template=edge_mask_template, num_layers=12, num_heads=12)

In [11]:
convert_mask_dict_to_params(acdcpp_mask_dict)

[tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
         0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 0.,
         1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.]),
 tensor([[1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1.]]),
 tensor([0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1.]),
 tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1

In [12]:
from cb_utils.transformer import DemoTransformer
from cb_utils.models import load_demo_gpt2, tokenizer
means_ioi = True
if means_ioi:
    with open("data/gpt2_ioi_abc_means.pkl", "rb") as f:
        means = pickle.load(f)[0]
else:
    with open("data/gpt2_means.pkl", "rb") as f:
        means = pickle.load(f)[0]

model = load_demo_gpt2(means=means, mask_dict_superset=acdcpp_mask_dict)

In [13]:
from tasks import IOITask, SportsTask, OWTTask
batch_size = 64
ioi = IOITask(batch_size=batch_size, tokenizer=tokenizer, device=device, prep_acdcpp=False)
sports = SportsTask(batch_size=batch_size, tokenizer=tokenizer, device=device)
owt = OWTTask(batch_size=batch_size, tokenizer=tokenizer, device=device)

train_tasks = {"ioi": ioi, "owt": owt}
task_weights = {"ioi": -.5, "owt": 1} # I think means preserve OWT, corrupt IOI
eval_tasks = {"ioi": ioi, "sports": sports, "owt": owt}

/data/phillip_guo/miniconda3/envs/unlrn/lib/python3.10/site-packages/datasets/table.py:1421: FutureWarning: promote has been superseded by mode='default'.
  table = cls._concat_blocks(blocks, axis=0)


In [14]:
mask_params = []
param_names = []
for name, p in model.named_parameters():
    if p.requires_grad:
        param_names.append(name)
        mask_params.append(p)

In [15]:
print(torch.cuda.max_memory_allocated(device=device) / 1e9)

11.337863168


In [16]:
from cb_utils.learn_mask import train_masks

epochs_left = 200
steps_per_epoch = 10
lr = .05 # free
weight_decay = 0
evaluate_every = 1
clamp_every = 10 # 5 # free
threshold = 0.5
use_wandb = True
edge_mask_reg_strength = 10
weight_mask_reg_strength = None

optimizer = torch.optim.AdamW(mask_params, lr=lr, weight_decay=weight_decay)
train_masks(model, tasks=train_tasks, optimizer=optimizer, num_epochs=epochs_left, steps_per_epoch=steps_per_epoch,
            # param_names=param_names, mask_params=mask_params, 
            task_weights=task_weights, eval_tasks=eval_tasks, evaluate_every=evaluate_every,clamp_every=clamp_every, threshold=threshold, edge_mask_reg_strength=edge_mask_reg_strength, weight_mask_reg_strength=None, verbose=False, use_wandb=use_wandb)

wandb: Currently logged in as: philliphguo. Use `wandb login --relogin` to force relogin


  0%|          | 0/201 [00:00<?, ?it/s]

Epoch 0, step 0
Epoch 0, step 1
Epoch 0, step 2
Epoch 0, step 3
Epoch 0, step 4
Epoch 0, step 5
Epoch 0, step 6
Epoch 0, step 7
Epoch 0, step 8
Epoch 0, step 9
Epoch 0, step 9: train loss -101.27384948730469
Evaluating on ioi
Loss on ioi: 11.719074249267578
Evaluating on sports
Loss on sports: 6.064774036407471
Evaluating on owt


  0%|          | 1/201 [00:19<1:06:26, 19.93s/it]

Loss on owt: 3.8086142539978027
Clamping weights
Number of ablated edges: 5
Epoch 1, step 0
Epoch 1, step 1
Epoch 1, step 2
Epoch 1, step 3
Epoch 1, step 4
Epoch 1, step 5
Epoch 1, step 6
Epoch 1, step 7
Epoch 1, step 8
Epoch 1, step 9
Epoch 1, step 9: train loss -103.32403564453125
Evaluating on ioi
Loss on ioi: 15.892265319824219
Evaluating on sports
Loss on sports: 9.300385475158691
Evaluating on owt


  1%|          | 2/201 [00:39<1:04:28, 19.44s/it]

Loss on owt: 4.081206798553467
Epoch 2, step 0
Epoch 2, step 1


  1%|          | 2/201 [00:42<1:10:26, 21.24s/it]


KeyboardInterrupt: 

In [20]:
for name, p in model.named_parameters():
    if p.requires_grad:
        print(name, p)

output_mask Parameter containing:
tensor([  1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   

In [23]:
for name, p in zip(param_names, mask_params):
    if p.requires_grad:
        print(name, p)

output_mask Parameter containing:
tensor([  1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,   1.0000,   

In [ ]:
weight_mask_components = set()
# pass into DemoTransformer constructor to tell which components to mask

