In [1]:
%load_ext autoreload
%autoreload 2
from transformer_lens import HookedTransformer, ActivationCache
import os
import torch
import numpy as np
import pandas as pd
import datasets
import transformers
import pickle

from tasks import PileTask, OWTTask, InductionTask, GreaterThanTask
from tasks.ioi.IOITask import IOITask, IOITask_NPO, IOITask_Uniform
from tasks.induction.InductionTask import InductionTask, InductionTask_NPO, InductionTask_Uniform
from tasks.facts.SportsTask import SportsTask, SportsTask_NPO, SportsTask_Uniform

from tqdm.auto import tqdm

from transformers import GPT2Tokenizer, GPTNeoXTokenizerFast, AutoModelForCausalLM, AutoTokenizer

from datasets import load_dataset
train_dataset = load_dataset('monology/pile-uncopyrighted', split='train', streaming=True)


# Load Model

In [ ]:
os.environ['HF_TOKEN'] = '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'
model_name = 'google/gemma-2b'
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = HookedTransformer.from_pretrained(
    model_name,
    tokenizer=tokenizer,
    device='cuda',
    default_padding_side="right",
    fold_ln=False,
    fold_value_biases=False,
    center_writing_weights=False,
    dtype=torch.bfloat16
)


Gemma's activation function should be approximate GeLU and not exact GeLU.
Changing the activation function to `gelu_pytorch_tanh`.if you want to use the legacy `gelu`, edit the `model.config` to set `hidden_activation=gelu`   instead of `hidden_act`. See https://github.com/huggingface/transformers/pull/29402 for more details.
Loading checkpoint shards: 100%|██████████| 2/2 [00:02<00:00,  1.22s/it]


Loaded pretrained model google/gemma-2b into HookedTransformer


# Load Datasets

In [ ]:
from tasks import PileTask, OWTTask, InductionTask, GreaterThanTask
from tasks.ioi.IOITask import IOITask, IOITask_NPO, IOITask_Uniform
from tasks.induction.InductionTask import InductionTask, InductionTask_NPO, InductionTask_Uniform
from tasks.facts.SportsTask import SportsTask, SportsTask_NPO, SportsTask_Uniform
from tasks.facts.SportsTaskAdversarial import adversarial_sports_eval
from tasks.facts.SportsTaskSideEffects import run_side_effects_evals


train_batch_size = 10
eval_batch_size = 50

device = "cuda"
train_loss_type = "sports"
forget_sport = "basketball"
maintain_sport = None
# val_sport = "baseball"


sports_1mp = SportsTask(batch_size=train_batch_size, tokenizer=tokenizer, device=device, prep_acdcpp=False, criterion="log_1_minus_p", forget_sport_subset={forget_sport}, is_forget_dataset=True)

if maintain_sport is None:
    maintain_sports = SportsTask(batch_size=train_batch_size, tokenizer=tokenizer, device=device, prep_acdcpp=False, criterion="cross_entropy", forget_sport_subset={forget_sport}, is_forget_dataset=False)
else:
    maintain_sports = SportsTask(batch_size=train_batch_size, tokenizer=tokenizer, device=device, prep_acdcpp=False, criterion="cross_entropy", forget_sport_subset={maintain_sport}, is_forget_dataset=True)

train_pile = PileTask(batch_size=train_batch_size, tokenizer=tokenizer, device=device, ctx_length=100, shuffle=True, buffer_size=50000)
train_tasks = {"sports_1mp": (sports_1mp, .2), "maintain_sports": (maintain_sports, 1), "pile": (train_pile, 1)}

# want to eval on other sports
forget_sport_eval = SportsTask(batch_size=eval_batch_size, tokenizer=tokenizer, device=device, prep_acdcpp=False, criterion="cross_entropy", forget_sport_subset={forget_sport}, is_forget_dataset=True)
test_pile = PileTask(batch_size=eval_batch_size, tokenizer=tokenizer, device=device, ctx_length=100, shuffle=True, buffer_size=50000)

induction_eval = InductionTask(batch_size=eval_batch_size, tokenizer=tokenizer, prep_acdcpp=False, seq_len=15, device=device)
if maintain_sport is None:
    maintain_sports_eval = SportsTask(batch_size=eval_batch_size, tokenizer=tokenizer, device=device, prep_acdcpp=False, criterion="cross_entropy", forget_sport_subset={forget_sport}, is_forget_dataset=False)
    eval_tasks = {"induction": induction_eval, "pile": test_pile, "forget_sport": forget_sport_eval, "maintain_sport": maintain_sports_eval}
else:
    maintain_sport_eval = SportsTask(batch_size=eval_batch_size, tokenizer=tokenizer, device=device, prep_acdcpp=False, criterion="cross_entropy", forget_sport_subset={maintain_sport}, is_forget_dataset=True)
    val_sport_eval = SportsTask(batch_size=eval_batch_size, tokenizer=tokenizer, device=device, prep_acdcpp=False, criterion="cross_entropy", forget_sport_subset={val_sport}, is_forget_dataset=True)
    eval_tasks = {"induction": induction_eval, "pile": test_pile, "forget_sport": forget_sport_eval, "maintain_sport": maintain_sport_eval, "val_sport": val_sport_eval}


OpenAI API key not found, will not be able to run evaluations on Sports Trivia Task


Testing Code:

import random

def create_random_weight_mask_dicts(model):
    # Creates random weight masks for testing
    weight_mask_attn_dict = {}
    weight_mask_mlp_dict = {}

    for layer in range(model.cfg.n_layers):
        weight_mask_attn_dict[layer] = {}
        # Want bool of length n_head, randomly set to True
        weight_mask_attn_dict[layer]['W_Q'] = torch.rand(model.cfg.n_heads) < 0.8
        weight_mask_attn_dict[layer]['W_K'] = torch.rand(model.cfg.n_heads) < 0.8
        weight_mask_attn_dict[layer]['W_V'] = torch.rand(model.cfg.n_heads) < 0.8
        weight_mask_attn_dict[layer]['W_O'] = torch.rand(model.cfg.n_heads) < 0.8

        # Randomly set to true or false
        weight_mask_mlp_dict[layer] = random.randint(0, 1) == 1

    return weight_mask_attn_dict, weight_mask_mlp_dict


# Weight Masking Wrapper

In [ ]:
from torch import nn

def make_partly_differentiable_mask(W, unfrozen_heads, device="cuda"):
    """
    W is Parameter of shape (n_heads, ...). Returns baseline and frozen (both only 1d arrays of (n_heads,)), and forward pass should be W_baseline.float() + W_frozen.float() * W 
    """
    W_baseline = torch.nn.Parameter(torch.zeros(W.shape[0], dtype=torch.bool), requires_grad=False).to(device)

    # unsqueeze to broadcast efficiently, until W_baseline has same shape as W
    while len(W_baseline.shape) < len(W.shape):
        W_baseline = W_baseline.unsqueeze(-1)
    
    W_baseline[unfrozen_heads] = True
    # W_baseline = ~W_frozen
    W_frozen = torch.nn.Parameter(~W_baseline, requires_grad=False)
    # convert into float
    return W_frozen.float(), W_baseline.float()

class WeightMaskedTransformer(nn.Module):
    def __init__(self, tl_transformer, weight_mask_attn_dict=None, weight_mask_mlp_dict=None, torch_dtype=torch.bfloat16):
        """
        weight_mask_attn_dict: {layer: {"W_Q": unfrozen_heads, "W_K": unfrozen_heads, "W_V": unfrozen_heads, "W_O": unfrozen_heads}} (frozen_heads is shape (n_heads,) of bools). If none, train mask over all heads
        weight_mask_mlp_dict: {layer: bool}. If none, train mask over all mlps

        """
        super().__init__()
        self.torch_dtype = torch_dtype
        # tl_transformer should be a HookedTransformer
        self.tl_transformer = tl_transformer
        # turn off gradients for tl_transformer
        # for param in self.tl_transformer.parameters():
        #     param.requires_grad = False

        self.weight_mask_attn_dict = weight_mask_attn_dict
        self.weight_mask_mlp_dict = weight_mask_mlp_dict
        # store weight masks for every component that is unfrozen
        
        # need to store reference weights so that you can reset W_Q, etc after a forward pass
        self.reference_attn_weights = {}
        self.reference_mlp_weights = {}

        self.attention_masks = {}
        self.mlp_masks = {}
        for layer in range(tl_transformer.cfg.n_layers):
            self.attention_masks[layer] = {}
            self.reference_attn_weights[layer] = {}
            self.mlp_masks[layer] = {}
            self.reference_mlp_weights[layer] = {}
            # Attention heads
            for component, parameter in [("W_Q", tl_transformer.blocks[layer].attn.W_Q), ("W_K", tl_transformer.blocks[layer].attn.W_K), ("W_V", tl_transformer.blocks[layer].attn.W_V), ("W_O", tl_transformer.blocks[layer].attn.W_O)]:
                if self.weight_mask_attn_dict is None:
                    unfrozen_heads = list(range(tl_transformer.cfg.n_heads)) # all heads are unfrozen
                else:
                    unfrozen_heads = self.weight_mask_attn_dict[layer][component]
                # make frozen and baseline masks, and also a copy of the original weights

                if unfrozen_heads is not None and len(unfrozen_heads) > 0:
                    W_frozen, W_baseline = make_partly_differentiable_mask(parameter, unfrozen_heads)
                    weight_mask = nn.Parameter(torch.ones_like(parameter).type(torch_dtype), requires_grad=True)
                    
                    self.attention_masks[layer][component] = (W_frozen, W_baseline, weight_mask)
                    self.reference_attn_weights[layer][component] = parameter.clone()

            # MLPs

            for component, parameter in [("W_in", tl_transformer.blocks[layer].mlp.W_in), ("W_out", tl_transformer.blocks[layer].mlp.W_out)]:
                if self.weight_mask_mlp_dict is None or self.weight_mask_mlp_dict[layer][component]:
                    weight_mask = nn.Parameter(torch.ones_like(parameter).type(torch_dtype), requires_grad=True)

                    self.mlp_masks[layer][component] = weight_mask
                    self.reference_mlp_weights[layer][component] = parameter.clone()

                
    def forward(self, *args, **kwargs):
        for layer in range(self.tl_transformer.cfg.n_layers):
            for component, parameter in [("W_Q", self.tl_transformer.blocks[layer].attn.W_Q), ("W_K", self.tl_transformer.blocks[layer].attn.W_K), ("W_V", self.tl_transformer.blocks[layer].attn.W_V), ("W_O", self.tl_transformer.blocks[layer].attn.W_O)]:
                if self.weight_mask_attn_dict is None or component in self.attention_masks[layer]:
                    W_frozen, W_baseline, weight_mask = self.attention_masks[layer][component]
                    reference_data = self.reference_attn_weights[layer][component]
                    mask = W_baseline + W_frozen * weight_mask
                    self.tl_transformer.blocks[layer].attn.__dict__['_parameters'][component] = reference_data * mask

            for component, parameter in [("W_in", self.tl_transformer.blocks[layer].mlp.W_in), ("W_out", self.tl_transformer.blocks[layer].mlp.W_out)]:
                if self.weight_mask_mlp_dict is None or self.weight_mask_mlp_dict[layer][component]:
                    weight_mask = self.mlp_masks[layer][component]
                    reference_data = self.reference_mlp_weights[layer][component]
                    self.tl_transformer.blocks[layer].mlp.__dict__['_parameters'][component] = reference_data * weight_mask

        return self.tl_transformer(*args, **kwargs)

    def generate(self, *args, **kwargs):
        return self.tl_transformer.generate(*args, **kwargs)

    def regularization_loss(self):
        # Compute the L1 sparsity penalty using the masks
        loss = 0
        for layer in range(self.tl_transformer.cfg.n_layers):
            for component, parameter in [("W_Q", self.tl_transformer.blocks[layer].attn.W_Q), ("W_K", self.tl_transformer.blocks[layer].attn.W_K), ("W_V", self.tl_transformer.blocks[layer].attn.W_V), ("W_O", self.tl_transformer.blocks[layer].attn.W_O)]:
                if self.weight_mask_attn_dict is None or component in self.attention_masks[layer]:
                    W_frozen, W_baseline, weight_mask = self.attention_masks[layer][component]
                    loss += torch.sum(torch.abs(weight_mask - 1)) # We subtract 1 because we want to encourage the mask to be 1

            for component, parameter in [("W_in", self.tl_transformer.blocks[layer].mlp.W_in), ("W_out", self.tl_transformer.blocks[layer].mlp.W_out)]:
                if self.weight_mask_mlp_dict is None or self.weight_mask_mlp_dict[layer][component]:
                    weight_mask = self.mlp_masks[layer][component]
                    loss += torch.sum(torch.abs(weight_mask - 1))
        return loss
    
    def on_step_end(self):
        # Clip all the masks

        for layer in range(self.tl_transformer.cfg.n_layers):
            for component, parameter in [("W_Q", self.tl_transformer.blocks[layer].attn.W_Q), ("W_K", self.tl_transformer.blocks[layer].attn.W_K), ("W_V", self.tl_transformer.blocks[layer].attn.W_V), ("W_O", self.tl_transformer.blocks[layer].attn.W_O)]:
                if self.weight_mask_attn_dict is None or component in self.attention_masks[layer]:
                    W_frozen, W_baseline, weight_mask = self.attention_masks[layer][component]
                    weight_mask.data = torch.clamp(weight_mask.data, 0, 1)

            for component, parameter in [("W_in", self.tl_transformer.blocks[layer].mlp.W_in), ("W_out", self.tl_transformer.blocks[layer].mlp.W_out)]:
                if self.weight_mask_mlp_dict is None or self.weight_mask_mlp_dict[layer][component]:
                    weight_mask = self.mlp_masks[layer][component]
                    weight_mask.data = torch.clamp(weight_mask.data, 0, 1)


# Train Weight Mask

## Load Localization

In [ ]:
from collections import defaultdict

def get_mask_from_ap_graph(model, ap_graph, threshold):
    # Attention masks are of form:
    # {layer: {"W_Q": unfrozen_heads, "W_K": unfrozen_heads, "W_V": unfrozen_heads, "W_O": unfrozen_heads}}
    # MLP masks are of form:
    # {layer: bool}

    # Localizations are of form:
    # {alayer.head_{q,k,v,result}:int, mlayer_{in,out}: int}

    weight_mask_attn_dict = {}
    weight_mask_mlp_dict = {}

    for layer in range(model.cfg.n_layers):
        weight_mask_attn_dict[layer] = {}
        weight_mask_mlp_dict[layer] = {}

        if 'a0.0_q' in ap_graph:
            weight_mask_attn_dict[layer]['W_Q'] = torch.tensor(
                [
                    abs(ap_graph[f"a{layer}.{head}_q"]) > threshold 
                    for head in range(model.cfg.n_heads)
                ]
            )
        else:
            weight_mask_attn_dict[layer]['W_Q'] = None

        if 'a0.0_k' in ap_graph:
            weight_mask_attn_dict[layer]['W_K'] = torch.tensor(
                [
                    abs(ap_graph[f"a{layer}.{head}_k"]) > threshold 
                    for head in range(model.cfg.n_heads)
                ]
            )
        else:
            weight_mask_attn_dict[layer]['W_K'] = None
        
        if 'a0.0_v' in ap_graph:
            weight_mask_attn_dict[layer]['W_V'] = torch.tensor(
                [
                    abs(ap_graph[f"a{layer}.{head}_v"]) > threshold 
                    for head in range(model.cfg.n_heads)
                ]
            )
        else:
            weight_mask_attn_dict[layer]['W_V'] = None
        
        if 'a0.0_result' in ap_graph:
            weight_mask_attn_dict[layer]['W_O'] = torch.tensor(
                [
                    abs(ap_graph[f"a{layer}.{head}_result"]) > threshold 
                    for head in range(model.cfg.n_heads)
                ]
            )
        else:
            weight_mask_attn_dict[layer]['W_O'] = None
            
        if 'm0_in' in ap_graph:
            weight_mask_mlp_dict[layer]['W_in'] = abs(ap_graph[f"m{layer}_in"]) > threshold
        else:
            weight_mask_mlp_dict[layer]['W_in'] = None
        
        if 'm0_out' in ap_graph:
            weight_mask_mlp_dict[layer]['W_out'] = abs(ap_graph[f"m{layer}_out"]) > threshold
        else:
            weight_mask_mlp_dict[layer]['W_out'] = None

    return weight_mask_attn_dict, weight_mask_mlp_dict


In [ ]:
import pickle
with open("models/google_gemma-2b_sports_baseball_ap_graph.pkl", "rb") as f:
    ap_graph = pickle.load(f)

weight_mask_attn_dict, weight_mask_mlp_dict = get_mask_from_ap_graph(model, ap_graph, 0.05)


mask = WeightMaskedTransformer(
    model, 
    weight_mask_attn_dict=weight_mask_attn_dict, 
    weight_mask_mlp_dict=weight_mask_mlp_dict
)
# for n, param in mask.tl_transformer.named_parameters():
#     param.requires_grad = False
sports_train = SportsTask(batch_size=8, tokenizer=tokenizer)
with torch.autocast(device_type="cuda"):
    loss = sports_train.get_train_loss(mask, 1)
    print(loss)
    loss.backward()
print(mask.attention_masks[3]['W_Q'][-1].grad[4])


In [ ]:
import gc
import wandb
gc.collect()
torch.cuda.empty_cache()

mask = WeightMaskedTransformer(
    model, 
    weight_mask_attn_dict=weight_mask_attn_dict, 
    weight_mask_mlp_dict=weight_mask_mlp_dict
)
for param in mask.tl_transformer.parameters():
    param.requires_grad = False 

model_type = 'gemma'
learning_rate = 1000
n_epochs = 50
grad_accum_steps = 5
# max_gpu_batch_size=8
alpha = 0.2
beta = 1
clip_grad = 1

evaluate_every = 5
n_eval_iters = 5
do_adversarial_evals = False
do_side_effects_evals = False 


wandb.init(
    # set the wandb project where this run will be logged
    project="mech-unlearning",
    name=f"{model_name.split('/')[-1]}-{forget_sport}",

    # track hyperparameters and run metadata
    config={
        "model_type": model_type,
        "model_name": model_name,
        "forget_sport": forget_sport,
        "learning_rate": learning_rate,
        "n_epochs": n_epochs,
        "grad_accum_steps": grad_accum_steps,
        "alpha": alpha,
        "beta": beta,
        "clip_grad": clip_grad,
        "evaluate_every": evaluate_every,
        "n_eval_iters": n_eval_iters,
        "do_adversarial_evals": do_adversarial_evals,
        "do_side_effects_evals": do_side_effects_evals,
    }
)

from collections import defaultdict
all_train_losses = defaultdict(list)
all_test_losses = defaultdict(list)
adversarial_evals = []
side_effect_evals = []

# Initialize optimizer
mask = mask.cuda()
# mask_params = [
#     v[-1]
#     for layer, layer_mask_weights in mask.attention_masks.items()
#     for k, v in layer_mask_weights.items()
# ] + \
# [
#     v
#     for layer, layer_mask_weights in mask.mlp_masks.items()
#     for k, v in layer_mask_weights.items()
# ]
optimizer = torch.optim.AdamW(mask.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer=optimizer, T_max=n_epochs)
# Cycle dataloaders
# Train a sparse mask
pbar = tqdm(range(n_epochs))
for epoch in pbar:
    # Sample batches
    # Reset grad
    optimizer.zero_grad()

    with torch.autocast(device_type="cuda"):
        # Compute normal loss over retain
        for task_name, (task, task_weight) in train_tasks.items():
            task_loss = 0
            # print(task_name)
            for i in range(grad_accum_steps):
                loss = task.get_train_loss(mask) / grad_accum_steps
                task_loss += loss.item()
                loss *= task_weight
                loss.backward()

                gc.collect()
                torch.cuda.empty_cache()
            all_train_losses[task_name].append(task_loss)

            gc.collect()
            torch.cuda.empty_cache()
            
        gc.collect()
        torch.cuda.empty_cache()
        # Add sparsity loss and backprop
        loss = beta * mask.regularization_loss()
        loss.backward()
        all_train_losses["reg"].append(loss.item())
        # Step and log
        if clip_grad is not None:
            torch.nn.utils.clip_grad_norm_(mask.parameters(), clip_grad)
        # zero_nan_grads(mask)
        optimizer.step()
        mask.on_step_end()
        scheduler.step()

        print(mask.attention_masks[3]['W_Q'][-1].grad[4])
        print(mask.attention_masks[3]['W_Q'][-1])
        print((mask.attention_masks[3]['W_Q'][-1] - 1).sum())

        if epoch % evaluate_every == 0 or epoch == n_epochs - 1:
            for task_name, task in eval_tasks.items():
                task_loss = 0
                for i in range(n_eval_iters):
                    task_loss += task.get_test_loss(mask).item()
                all_test_losses[task_name].append(task_loss / n_eval_iters)
            if do_adversarial_evals:
                print("Running adversarial evals")
                adversarial_evals.append(adversarial_sports_eval(mask, model_type=model_type, batch_size=eval_batch_size, use_system_prompt=True))
            if do_side_effects_evals:
                print("Running side effects evals")
                side_effect_evals.append(run_side_effects_evals(mask, model_type=model_type, batch_size=eval_batch_size, evals_to_run=["Sports Answers"]))
        
        # log_dict = {}
        # for k, v in all_train_losses.items():
        #     log_dict[f"train_loss_{k}"] = v[-1]
        # for k, v in all_test_losses.items():
        #     log_dict[f"test_loss_{k}"] = v[-1]
        # for k, v in adversarial_evals[-1].items():
        #     log_dict[f"adversarial_{k}"] = v
        # for k, v in side_effect_evals[-1].items():
        #     log_dict[f"side_effects_{k}"] = v
        # wandb.log(log_dict)
    
wandb.finish()
        

Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Currently logged in as: aaquib111. Use `wandb login --relogin` to force relogin


  0%|          | 0/50 [00:00<?, ?it/s]

tensor([[-2.7195e-07, -3.7951e-08,  2.0862e-07,  ...,  2.0675e-07,
          6.7987e-08, -2.4028e-07],
        [-1.1222e-07, -3.5390e-07,  2.6077e-08,  ...,  2.2501e-06,
          4.7963e-08,  1.8179e-06],
        [-1.9092e-08, -1.0186e-09, -4.8312e-09,  ..., -6.8685e-09,
          1.9558e-08,  2.6077e-08],
        ...,
        [ 1.7788e-07, -1.0524e-07, -6.3330e-08,  ..., -4.0978e-07,
          2.0256e-08,  2.4587e-07],
        [ 3.0547e-07, -1.9099e-10, -9.7323e-08,  ...,  1.0151e-07,
          2.4447e-08,  4.4517e-07],
        [ 2.3283e-09,  1.2759e-07, -3.6089e-09,  ...,  3.0100e-06,
         -2.0266e-06, -1.2293e-06]], device='cuda:0', dtype=torch.bfloat16)
Parameter containing:
tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
    

  4%|▍         | 2/50 [00:58<21:32, 26.92s/it]

tensor([[-3.8929e-07, -6.1467e-08,  2.1327e-07,  ..., -1.6298e-07,
          3.5390e-08, -2.4401e-07],
        [-1.1316e-07, -3.9116e-07, -3.1723e-09,  ...,  4.6492e-06,
         -5.3551e-08,  2.3246e-06],
        [-2.3749e-08, -1.5018e-08,  3.1898e-08,  ...,  5.7742e-08,
         -1.4622e-07,  1.1455e-07],
        ...,
        [ 2.0396e-07, -1.8626e-07, -3.9348e-08,  ..., -7.8976e-07,
          2.6077e-08,  3.4645e-07],
        [ 4.3213e-07, -4.2201e-10, -1.2293e-07,  ..., -7.6368e-08,
         -1.4901e-07,  3.9674e-07],
        [ 6.9558e-09,  1.8999e-07, -2.8638e-08,  ...,  5.5134e-06,
         -2.9057e-06,  4.3213e-06]], device='cuda:0', dtype=torch.bfloat16)
Parameter containing:
tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
    

  6%|▌         | 3/50 [01:13<16:37, 21.22s/it]

tensor([[-4.2096e-07, -7.0315e-08,  2.8498e-07,  ..., -5.8860e-07,
         -3.5856e-08, -6.6310e-07],
        [-1.1781e-07, -4.6007e-07, -4.0047e-08,  ...,  6.5565e-06,
         -1.9744e-07, -1.5646e-06],
        [-2.7241e-08, -1.5600e-08,  7.1712e-08,  ...,  1.6298e-07,
          3.7020e-08,  1.0058e-07],
        ...,
        [ 2.0675e-07, -1.4994e-07, -3.9814e-08,  ..., -1.2144e-06,
          3.9116e-08,  4.3213e-07],
        [ 4.8801e-07, -4.6566e-10, -1.9185e-07,  ...,  8.1956e-07,
         -1.9372e-07,  4.4890e-07],
        [ 1.9936e-09,  1.6298e-07, -3.2596e-08,  ...,  6.7651e-06,
         -2.2352e-06,  7.2122e-06]], device='cuda:0', dtype=torch.bfloat16)
Parameter containing:
tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
    

  8%|▊         | 4/50 [01:27<14:10, 18.49s/it]

tensor([[-5.2899e-07, -7.3109e-08,  2.8498e-07,  ..., -6.4075e-07,
          6.1700e-09, -8.9779e-07],
        [-1.1735e-07, -6.3330e-07, -3.7486e-08,  ...,  6.7949e-06,
          4.3400e-07,  1.0571e-07],
        [-4.1444e-08, -2.3632e-08,  9.9652e-08,  ...,  1.8906e-07,
         -2.1886e-07,  9.9186e-08],
        ...,
        [ 1.6205e-07, -1.6019e-07, -4.4238e-08,  ..., -1.5944e-06,
          3.7719e-08,  5.2899e-07],
        [ 5.8115e-07, -5.6389e-10, -1.3597e-07,  ...,  1.5274e-07,
         -1.1781e-07,  5.7369e-07],
        [ 1.0245e-08,  1.8813e-07, -3.7951e-08,  ...,  9.7752e-06,
         -3.0100e-06,  9.6560e-06]], device='cuda:0', dtype=torch.bfloat16)
Parameter containing:
tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
    

 10%|█         | 5/50 [01:41<12:42, 16.95s/it]

tensor([[-3.9302e-07, -4.8894e-08,  2.4959e-07,  ..., -7.9721e-07,
          3.0268e-08, -8.1956e-07],
        [-1.0524e-07, -4.4703e-07, -3.5856e-08,  ...,  7.3612e-06,
          3.6694e-07,  2.9057e-07],
        [-3.2131e-08, -1.0070e-08,  1.0896e-07,  ...,  5.2527e-07,
         -3.8743e-07,  5.2154e-08],
        ...,
        [ 2.4959e-07, -1.8068e-07, -4.7730e-08,  ..., -1.8403e-06,
          2.4680e-08,  4.7684e-07],
        [ 5.8115e-07, -5.4570e-10, -1.4994e-07,  ..., -3.7951e-08,
         -4.2096e-07,  4.7311e-07],
        [ 2.5146e-08,  2.0489e-07, -3.3528e-08,  ...,  1.0431e-05,
         -3.2485e-06,  1.2100e-05]], device='cuda:0', dtype=torch.bfloat16)
Parameter containing:
tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
    

 14%|█▍        | 7/50 [02:18<12:27, 17.38s/it]

tensor([[-5.0291e-07,  7.6834e-09,  4.2142e-08,  ...,  1.6997e-08,
          9.6392e-08, -9.7603e-07],
        [-1.5181e-07, -8.4192e-07, -3.0501e-08,  ...,  6.0797e-06,
          6.2212e-07,  2.4885e-06],
        [-2.5611e-09, -3.0734e-08,  7.1712e-08,  ...,  9.9838e-07,
         -1.0878e-06, -7.5903e-08],
        ...,
        [ 1.9372e-07,  3.7289e-10, -7.5903e-08,  ..., -1.5721e-06,
          3.8883e-08,  5.2154e-07],
        [ 7.4506e-07, -4.5475e-10,  3.4645e-07,  ..., -2.6822e-06,
          4.6007e-07, -1.4305e-06],
        [ 2.8871e-08,  2.9057e-07, -6.1002e-08,  ...,  1.4007e-05,
          1.6689e-06,  4.0531e-06]], device='cuda:0', dtype=torch.bfloat16)
Parameter containing:
tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
    

 16%|█▌        | 8/50 [02:32<11:28, 16.39s/it]

tensor([[-3.9861e-07, -4.0454e-09,  4.7730e-08,  ..., -3.1106e-07,
          1.4610e-08, -1.3337e-06],
        [-8.1025e-08, -3.0920e-07, -4.1211e-08,  ...,  5.0068e-06,
          4.8429e-07,  1.1399e-06],
        [ 2.2002e-08, -3.0966e-08,  7.2177e-08,  ...,  9.6858e-07,
         -8.8289e-07, -4.9360e-08],
        ...,
        [ 1.2107e-07,  2.6892e-08, -6.4727e-08,  ..., -1.7062e-06,
          3.9348e-08,  4.1723e-07],
        [ 7.2271e-07, -4.5111e-10,  3.0920e-07,  ..., -2.1160e-06,
          6.2585e-07, -1.1474e-06],
        [ 3.7719e-08,  2.2538e-07, -7.9162e-08,  ...,  1.2338e-05,
          7.5251e-07,  3.7402e-06]], device='cuda:0', dtype=torch.bfloat16)
Parameter containing:
tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
    

 18%|█▊        | 9/50 [02:48<10:54, 15.97s/it]

tensor([[-3.9302e-07, -1.2224e-08,  1.8440e-07,  ..., -1.8440e-07,
         -7.5670e-09, -1.5125e-06],
        [-8.8010e-08, -4.3958e-07, -3.7486e-08,  ...,  5.8115e-06,
          4.7125e-07,  2.0415e-06],
        [ 4.8894e-08, -3.4226e-08,  1.0012e-07,  ...,  1.5348e-06,
         -1.1995e-06, -2.6659e-08],
        ...,
        [ 6.2864e-08,  6.0070e-08, -4.6799e-08,  ..., -1.8477e-06,
          4.1677e-08,  4.0233e-07],
        [ 6.8918e-07, -4.5111e-10,  3.8184e-07,  ..., -1.2293e-06,
          4.9919e-07, -1.2890e-06],
        [ 3.7719e-08,  1.5367e-07, -7.2177e-08,  ...,  1.1504e-05,
         -2.1607e-07,  4.6194e-06]], device='cuda:0', dtype=torch.bfloat16)
Parameter containing:
tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
    

# Evals

In [8]:
# Final evals
final_adversarial_eval = adversarial_sports_eval(model, model_type=model_type, batch_size=eval_batch_size, use_system_prompt=True)
print(f"System Prompt: adversarial evals are {final_adversarial_eval}")
final_adversarial_eval = adversarial_sports_eval(model, model_type=model_type, batch_size=eval_batch_size, use_system_prompt=False)
print(f"No System Prompt: adversarial evals are {final_adversarial_eval}")

final_side_effects = run_side_effects_evals(model, model_type=model_type, batch_size=eval_batch_size, evals_to_run=["Sports Answers", "Sports Familiarity", "Cross Entropy"], verbose=True)
print(final_side_effects)


KeyboardInterrupt: 

In [29]:
weight_mask_mlp_dict[10]


{'W_in': False, 'W_out': True}

In [37]:
(mask.mlp_masks[5]['W_out'] - 1).sum()


tensor(0., device='cuda:0', dtype=torch.bfloat16, grad_fn=<SumBackward0>)

# Save Mask

In [ ]:
# save masks state dict to neuron_cb
torch.save(mask.state_dict(), "masks/neuron_cb/mlps_unlearn_basketball.pt")
